common.h
SHM_SEGMENT_NAME
SHM_BUFFER_SIZE
GEN_BUFFER_SIZE
MAX_MESSAGES
MICROS_PER_SEC
request_e
exit_e
typedef struct thread_id_s thread_id_s
void print_header(char *buffer)
Write a string formatted with the TID of the thread calling this function and a timestamp to the log buffer.
================================================================================= Function: print_header *buffer - pointer to where we should copy formatted string to if NULL, we print to stderr void
Referenced by light_fn, socket_init, temperature_fn.
void thread_exit(int exit_status)
Common exit point for all threads.
================================================================================= Function: thread_exit exit_status - reason for exit (signal number) void
Referenced by sig_handler, socket_fn.
void* get_shared_memory(void)
Sets up shared memory location for logging.
================================================================================= Function: get_shared_memory void *shm_p - pointer to shared memory object
Referenced by light_fn, socket_fn, temperature_fn.
int sems_init(shared_data_t *shm)
================================================================================= Function: sems_init Initialize semaphores for shared memory *shm - pointer to shared memory object EXIT_CLEAN if successful, otherwise EXIT_INIT
int timer_setup(timer_t *id, void(*timer_handler)(union sigval))
Initializes a timer identified by timer_t id.
================================================================================= Function: timer_setup *id - identifier for new timer *handler - pointer to function to register as the handler for the timer ticks EXIT_CLEAN if successful, otherwise EXIT_INIT
int timer_start(timer_t *id, unsigned long usecs)
Starts the timer with interval usecs.
================================================================================= Function: timer_start *id - identifier for new timer usecs - timer interval EXIT_CLEAN if successful, otherwise EXIT_INIT