i2c.c
i2c_handle_t* my_i2c
Keep around a singleton instance of the master handle
Referenced by i2c_init.
int i2c_set(int slave, int addr)
int i2c_write_byte(int slave, int reg, uint8_t data)
Writes byte to register address.
================================================================================= Function: i2c_write_byte slave - address of i2c slave reg - address of register to write to data - data to write EXIT_CLEAN on success, otherwise one of exit_e
Referenced by apds9301_power.
int i2c_write(int slave, int reg, uint16_t data)
Writes data to register address.
================================================================================= Function: i2c_write slave - address of i2c slave reg - address of register to write to data - data to write EXIT_CLEAN on success, otherwise one of exit_e
Referenced by apds9301_write_threshold_low, apds9301_write_threshold_high, tmp102_write_config, tmp102_write_thigh, tmp102_write_tlow.
int i2c_read(int slave, int reg, uint8_t *data, size_t len)
Reads data from register address.
================================================================================= Function: i2c_read slave - address of i2c slave reg - address to read from *data - pointer to location to store read data len - size of memory to read in bytes EXIT_CLEAN on success, otherwise one of exit_e
Referenced by apds9301_set_interrupt, apds9301_set_gain, apds9301_read_control, apds9301_read_threshold_low, apds9301_read_threshold_high, apds9301_read_id, apds9301_read_data0, apds9301_read_data1, tmp102_get_temp, tmp102_read_thigh, tmp102_read_tlow.
int i2c_init(i2c_handle_t *i2c)
Initialize singleton master i2c context.
================================================================================= Function: i2c_init *i2c - pointer to handle to be master EXIT_CLEAN on success, otherwise EXIT_INIT
int i2c_stop(i2c_handle_t *i2c)
Stops i2c instance.
================================================================================= Function: i2c_stop *i2c - pointer to i2c context handle EXIT_CLEAN on success, otherwise EXIT_ERROR