led.h
LED0_PATH
LED1_PATH
LED2_PATH
LED3_PATH
LED_BRIGHTNESS
LED_TRIGGER
LED_DELAYON
LED_DELAYOFF
LED0_BRIGHTNESS
LED1_BRIGHTNESS
LED2_BRIGHTNESS
LED3_BRIGHTNESS
LED0_TRIGGER
LED1_TRIGGER
LED2_TRIGGER
LED3_TRIGGER
LED0_DELAYON
LED1_DELAYON
LED2_DELAYON
LED3_DELAYON
LED0_DELAYOFF
LED1_DELAYOFF
LED2_DELAYOFF
LED3_DELAYOFF
void get_status(const char *led)
================================================================================= Function: get_status <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
int set_trigger(const char *led, char *trigger)
================================================================================= Function: get_trigger <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
int set_delay(const char *led_path, int delay)
================================================================================= Function: set_delay <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
void led_on(const char *led)
================================================================================= Function: led_on <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
Referenced by led_toggle.
void led_off(const char *led)
================================================================================= Function: led_off <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
Referenced by led_toggle, turn_off_leds.
void led_toggle(const char *led)
================================================================================= Function: led_toggle <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
Referenced by timer_handler.