led.c
void get_status(const char *led)
================================================================================= Function: get_status <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
int set_trigger(const char *led, char *trigger)
================================================================================= Function: get_trigger <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
int set_delay(const char *led, int delay)
================================================================================= Function: set_delay <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
void led_on(const char *led)
================================================================================= Function: led_on <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
Referenced by led_toggle.
void led_off(const char *led)
================================================================================= Function: led_off <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
Referenced by led_toggle, turn_off_leds.
void led_toggle(const char *led)
================================================================================= Function: led_toggle <+NAME+> <+DESCRIPTION+> <+DESCRIPTION+> <+DETAILED+>
Referenced by timer_handler.