light.c
timer_t timerid
struct itimerspec trigger
i2c_handle_t i2c_apds9301
float last_lux_value
mqd_t light_queue
shared_data_t* shm
static void sig_handler(int signo)
Signal handler for light sensor thread. On normal operation, we should be receving SIGUSR1/2 signals from watchdog when prompted to exit. So, we close the message queue and timer this thread owns.
================================================================================= Function: sig_handler signo - enum with signal number of signal being handled void
Referenced by light_fn.
static void timer_handler(union sigval sig)
Timer handler function for light sensor thread When woken up by the timer, get lux reading and write state to shared memory.
================================================================================= Function: timer_handler sig void
float get_lux(void)
Returns last lux reading.
================================================================================= Function: get_lux void last_lux_value - last lux reading we have
int is_dark(void)
Returns int speciyfing if it is night or day.
================================================================================= Function: is_dark void night - 0 if it is day, 1 if night, i.e. below DARK_THRESHOLD
int apds9301_set_config(void)
Set configuration of light sensor. For the APDS9301, the configuration is spread out across the: Timing Register, Interrupt Control Register, and Control Register. So, I have to write to all of these to set the config.
================================================================================= Function: apds9301_set_config void EXIT_CLEAN if successful, otherwise see i2c_write()
int apds9301_set_integration(uint8_t val)
Sets the integration time for APDS9301 by writing a value to bits INTEG of the Timing Register.
================================================================================= Function: apds9301_set_integration val - value to write to timing register see i2c_write_byte() - if val is not an allowed value, EXIT_ERROR
int apds9301_clear_interrupt(void)
Clears any pending interrupt for APDS9301 by writing a 1 to the CLEAR bit of the Command Register.
================================================================================= Function: apds9301_clear_interrupt void see i2c_set()
int apds9301_set_interrupt(uint8_t enable)
Enables or disables interrupts for APDS9301 by setting or clearing the INTR bits of the Interrupt Control Register.
================================================================================= Function: apds9301_set_interrupt enable - set if we want to enable interrupts see i2c_write_byte()
Referenced by apds9301_set_config.
int apds9301_set_gain(uint8_t gain)
Sets gain for APDS9301 by setting or clearing the GAIN bit of the Timing Register.
================================================================================= Function: apds9301_set_gain gain - set if we want high gain see i2c_write_byte()
Referenced by apds9301_set_config.
int apds9301_read_control(uint8_t *data)
Read contents of Control Register.
================================================================================= Function: apds9301_read_control *data - where to store contents see i2c_read()
int apds9301_write_threshold_low(uint16_t threshold)
Write value to low threshold register.
================================================================================= Function: apds9301_write_threshold_low threshold - value to write see i2c_write()
int apds9301_read_threshold_low(uint16_t *threshold)
Read value from low threshold register.
================================================================================= Function: apds9301_write_threshold_low *threshold - where to write value read see i2c_write()
int apds9301_write_threshold_high(uint16_t threshold)
Write value to high threshold register.
================================================================================= Function: apds9301_write_threshold_high threshold - value to write see i2c_write()
int apds9301_read_threshold_high(uint16_t *threshold)
Read value from high threshold register.
================================================================================= Function: apds9301_write_threshold_high *threshold - where to write value read see i2c_write()
int apds9301_read_id(uint8_t *id)
Read APDS9301 Identification Register.
================================================================================= Function: apds9301_read_id *id - where to write ID from register see i2c_read()
int apds9301_get_lux(float *lux)
Read ADC Registers and calculate lux in lumen using equations from APDS9301 datasheet.
Read ADC Registers and calculate lux in lumen.================================================================================= Function: apds9301_get_lux *lux - pointer to location to write decoded lux to EXIT_CLEAN if successful, otherwise EXIT_ERROR
int apds9301_read_data0(uint16_t *data)
Read ADC register for channel 0.
================================================================================= function: apds9301_read_data0 *data - pointer to location to write decoded value to EXIT_CLEAN if successful, otherwise exit_error
Referenced by apds9301_get_lux.
int apds9301_read_data1(uint16_t *data)
Read ADC register for channel 1.
================================================================================= function: apds9301_read_data1 *data - pointer to location to write decoded value to EXIT_CLEAN if successful, otherwise exit_error
int apds9301_power(uint16_t on)
power on (or off) APDS9301 as set by paramater
================================================================================= Function: apds9301_power on - specifies if sensor is to be powered on or off see i2c_write_byte()
static void cycle(void)
Cycle function for light sensor thread We wait in this while loop checking for requests from watchdog for health status.
================================================================================= Function: cycle void void
mqd_t get_light_queue(void)
Get file descriptor for light sensor thread. Called by watchdog thread in order to be able to send heartbeat check via queue.
================================================================================= Function: get_light_queue void temp_queue - file descriptor for light sensor thread message queue
int light_queue_init(void)
Initialize message queue for light sensor thread.
================================================================================= Function: light_queue_init void msg_q - file descriptor for initialized message queue
void* light_fn(void *thread_args)
Entry point for light sensor processing thread.
================================================================================= Function: light_fn thread_args - void ptr to arguments used to initialize thread NULL - We don't really exit from this function, since the exit point is thread_exit()